season:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/criminal?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      password: 16893714
      username: root